/* eslint-disable react-refresh/only-export-components */
import React, { createContext, useState, useContext } from "react";

// Full UI translation dictionary for all supported languages
export const LANGUAGES = [
  { name: "English", code: "en-IN" },
  { name: "Hindi", code: "hi-IN" },
  { name: "Gujarati", code: "gu-IN" },
  { name: "Tamil", code: "ta-IN" },
  { name: "Telugu", code: "te-IN" },
  { name: "Marathi", code: "mr-IN" },
  { name: "Bengali", code: "bn-IN" },
  { name: "Kannada", code: "kn-IN" },
  { name: "Punjabi", code: "pa-IN" },
  { name: "Odia", code: "or-IN" },
];

export const UI_STRINGS = {
  English: {
    customerChat: "Customer Chat",
    adminDashboard: "Admin Dashboard",
    voiceMode: "Voice Mode",
    language: "Language",
    aiOnline: "AI Online",
    assistantTracking: "Assistant tracking",
    mode: "Mode",
    typeQuery: "Type your query or click mic to speak...",
    send: "Send",
    quickChips: [
      "Account balance",
      "Fund transfer",
      "Loan status",
      "Complaint",
      "Block card",
    ],
    welcomeMsg:
      "Hello! I am BranchIQ, your AI banking assistant. I can help you with account balance, fund transfers, loan status, complaints, and more. How can I assist you today?",
    voiceTitle: "Voice Self-Service",
    voiceSubtitle: "Click the mic and speak your banking query",
    clickMic: "Click mic to start speaking",
    listening: "Listening... speak now",
    processing: "Processing your query...",
    speakAgain: "Click mic to speak again",
    transcript: "Your transcript will appear here...",
    queriesDay: "Queries Today",
    resolutionRate: "Resolution Rate",
    avgResTime: "Avg Res Time",
    escalated: "Escalated",
    recentQueries: "Recent Queries",
    escalationQueue: "Escalation Queue",
    assignAgent: "Assign to Agent",
    queueClear: "Queue is clear! All customers served.",
    status: "Status",
    query: "Query",
    lang: "Lang",
    time: "Time",
  },
  Hindi: {
    customerChat: "ग्राहक चैट",
    adminDashboard: "व्यवस्थापक डैशबोर्ड",
    voiceMode: "वॉइस मोड",
    language: "भाषा",
    aiOnline: "AI ऑनलाइन",
    assistantTracking: "सहायक ट्रैकिंग",
    mode: "मोड",
    typeQuery: "अपना प्रश्न टाइप करें या माइक पर क्लिक करें...",
    send: "भेजें",
    quickChips: [
      "खाता शेष",
      "फंड ट्रांसफर",
      "लोन स्थिति",
      "शिकायत",
      "कार्ड ब्लॉक",
    ],
    welcomeMsg:
      "नमस्ते! मैं BranchIQ हूं, आपका AI बैंकिंग सहायक। मैं खाता शेष, फंड ट्रांसफर, लोन स्थिति, शिकायत आदि में आपकी मदद कर सकता हूं।",
    voiceTitle: "वॉइस स्वयं-सेवा",
    voiceSubtitle: "माइक पर क्लिक करें और अपनी बैंकिंग क्वेरी बोलें",
    clickMic: "बोलना शुरू करने के लिए माइक पर क्लिक करें",
    listening: "सुन रहा हूं... अभी बोलें",
    processing: "आपकी क्वेरी प्रोसेस हो रही है...",
    speakAgain: "फिर बोलने के लिए माइक पर क्लिक करें",
    transcript: "आपका ट्रांसक्रिप्ट यहां दिखेगा...",
    queriesDay: "आज की क्वेरी",
    resolutionRate: "समाधान दर",
    avgResTime: "औसत समाधान समय",
    escalated: "एस्केलेटेड",
    recentQueries: "हाल की क्वेरी",
    escalationQueue: "एस्केलेशन कतार",
    assignAgent: "एजेंट को सौंपें",
    queueClear: "कतार साफ है! सभी ग्राहकों की सेवा हो गई।",
    status: "स्थिति",
    query: "क्वेरी",
    lang: "भाषा",
    time: "समय",
  },
  Gujarati: {
    customerChat: "ગ્રાહક ચેટ",
    adminDashboard: "એડમિન ડેશબોર્ડ",
    voiceMode: "વૉઇસ મોડ",
    language: "ભાષા",
    aiOnline: "AI ઓનલાઇન",
    assistantTracking: "સહાયક ટ્રેકિંગ",
    mode: "મોડ",
    typeQuery: "તમારી ક્વેરી ટાઇપ કરો અથવા માઇક ક્લિક કરો...",
    send: "મોકલો",
    quickChips: [
      "ખાતાની બેલેન્સ",
      "ભંડોળ ટ્રાન્સફર",
      "લોન સ્ટેટસ",
      "ફરિયાદ",
      "કાર્ડ બ્લૉક",
    ],
    welcomeMsg:
      "નમસ્તે! હું BranchIQ છું, તમારો AI બેન્કિંગ સહાયક. ગુજરાતીમાં પૂછો - ખાતાની બેલેન્સ, ટ્રાન્સ્ફર, લોન વગેરેમાં મદદ મળશે.",
    voiceTitle: "વૉઇસ સ્વ-સેવા",
    voiceSubtitle: "માઇક ક્લિક કરો અને તમારી બેન્કિંગ ક્વેરી બોલો",
    clickMic: "બોલવા માટે માઇક ક્લિક કરો",
    listening: "સાંભળી રહ્યો છું... હવે બોલો",
    processing: "તમારી ક્વેરી પ્રોસેસ હો રહી છે...",
    speakAgain: "ફરી બોલવા માટે માઇક ક્લિક કરો",
    transcript: "તમારું ટ્રાન્સ્ક્રિપ્ટ અહીં દેખાશે...",
    queriesDay: "આજની ક્વેરી",
    resolutionRate: "સોલ્યુશન દર",
    avgResTime: "સરેરાશ સોલ્યુશન સમય",
    escalated: "એસ્કેલેટ",
    recentQueries: "તાજેતરની ક્વેરી",
    escalationQueue: "એસ્કેલેશન કતાર",
    assignAgent: "એજન્ટને સોંપો",
    queueClear: "કતાર ખાલી! બધા ગ્રાહકોની સેવા થઈ.",
    status: "સ્થિતિ",
    query: "ક્વેરી",
    lang: "ભાષા",
    time: "સમય",
  },
  Tamil: {
    customerChat: "வாடிக்கையாளர் அரட்டை",
    adminDashboard: "நிர்வாக டாஷ்போர்டு",
    voiceMode: "குரல் முறை",
    language: "மொழி",
    aiOnline: "AI ஆன்லைன்",
    assistantTracking: "உதவியாளர் கண்காணிப்பு",
    mode: "முறை",
    typeQuery:
      "உங்கள் கேள்வியை தட்டச்சு செய்யுங்கள் அல்லது மைக்கை கிளிக் செய்யுங்கள்...",
    send: "அனுப்பு",
    quickChips: [
      "கணக்கு இருப்பு",
      "நிதி பரிமாற்றம்",
      "கடன் நிலை",
      "புகார்",
      "அட்டை தடை",
    ],
    welcomeMsg:
      "வணக்கம்! நான் BranchIQ, உங்கள் AI வங்கி உதவியாளர். தமிழில் கேளுங்கள் - கணக்கு இருப்பு, பரிமாற்றம், கடன் விவரங்கள் உதவி கிடைக்கும்.",
    voiceTitle: "குரல் சுய சேவை",
    voiceSubtitle: "மைக்கை கிளிக் செய்து உங்கள் வங்கி கேள்வியை பேசுங்கள்",
    clickMic: "பேச மைக்கை கிளிக் செய்யுங்கள்",
    listening: "கேட்கிறேன்... இப்போது பேசுங்கள்",
    processing: "உங்கள் கேள்வி செயலாக்கப்படுகிறது...",
    speakAgain: "மீண்டும் பேச மைக்கை கிளிக் செய்யுங்கள்",
    transcript: "உங்கள் டிரான்ஸ்கிரிப்ட் இங்கே தோன்றும்...",
    queriesDay: "இன்றைய கேள்விகள்",
    resolutionRate: "தீர்வு வீதம்",
    avgResTime: "சராசரி தீர்வு நேரம்",
    escalated: "அதிகரிக்கப்பட்டது",
    recentQueries: "சமீபத்திய கேள்விகள்",
    escalationQueue: "அதிகரிப்பு வரிசை",
    assignAgent: "முகவருக்கு ஒதுக்கு",
    queueClear:
      "வரிசை காலி! அனைத்து வாடிக்கையாளர்களுக்கும் சேவை செய்யப்பட்டது.",
    status: "நிலை",
    query: "கேள்வி",
    lang: "மொழி",
    time: "நேரம்",
  },
  Telugu: {
    customerChat: "కస్టమర్ చాట్",
    adminDashboard: "అడ్మిన్ డాష్‌బోర్డ్",
    voiceMode: "వాయిస్ మోడ్",
    language: "భాష",
    aiOnline: "AI ఆన్‌లైన్",
    assistantTracking: "అసిస్టెంట్ ట్రాకింగ్",
    mode: "మోడ్",
    typeQuery: "మీ ప్రశ్నను టైప్ చేయండి లేదా మైక్ క్లిక్ చేయండి...",
    send: "పంపు",
    quickChips: [
      "ఖాతా నిల్వ",
      "నిధుల బదిలీ",
      "రుణ స్థితి",
      "ఫిర్యాదు",
      "కార్డ్ బ్లాక్",
    ],
    welcomeMsg:
      "నమస్తే! నేను BranchIQ, మీ AI బ్యాంకింగ్ సహాయకుడు. తెలుగులో అడగండి - ఖాతా నిల్వ, బదిలీ, రుణ వివరాలు అందుబాటులో ఉన్నాయి.",
    voiceTitle: "వాయిస్ స్వయం-సేవ",
    voiceSubtitle: "మైక్ క్లిక్ చేసి మీ బ్యాంకింగ్ ప్రశ్న చెప్పండి",
    clickMic: "మాట్లాడటానికి మైక్ క్లిక్ చేయండి",
    listening: "వింటున్నాను... ఇప్పుడు మాట్లాడండి",
    processing: "మీ ప్రశ్న ప్రాసెస్ అవుతోంది...",
    speakAgain: "మళ్ళీ మాట్లాడటానికి మైక్ క్లిక్ చేయండి",
    transcript: "మీ ట్రాన్స్‌క్రిప్ట్ ఇక్కడ కనిపిస్తుంది...",
    queriesDay: "నేటి ప్రశ్నలు",
    resolutionRate: "పరిష్కార రేటు",
    avgResTime: "సగటు పరిష్కార సమయం",
    escalated: "ఎస్కలేటెడ్",
    recentQueries: "ఇటీవలి ప్రశ్నలు",
    escalationQueue: "ఎస్కలేషన్ క్యూ",
    assignAgent: "ఏజెంట్‌కు కేటాయించు",
    queueClear: "క్యూ ఖాళీ! అందరు కస్టమర్లకు సేవ అందించబడింది.",
    status: "స్థితి",
    query: "ప్రశ్న",
    lang: "భాష",
    time: "సమయం",
  },
  Marathi: {
    customerChat: "ग्राहक चॅट",
    adminDashboard: "व्यवस्थापक डॅशबोर्ड",
    voiceMode: "व्हॉइस मोड",
    language: "भाषा",
    aiOnline: "AI ऑनलाइन",
    assistantTracking: "सहाय्यक ट्रॅकिंग",
    mode: "मोड",
    typeQuery: "तुमचा प्रश्न टाइप करा किंवा माइक क्लिक करा...",
    send: "पाठवा",
    quickChips: [
      "खाते शिल्लक",
      "फंड ट्रान्सफर",
      "कर्ज स्थिती",
      "तक्रार",
      "कार्ड ब्लॉक",
    ],
    welcomeMsg:
      "नमस्कार! मी BranchIQ आहे, तुमचा AI बँकिंग सहाय्यक. मराठीत विचारा - खाते शिल्लक, ट्रान्सफर, कर्ज माहिती मिळेल.",
    voiceTitle: "व्हॉइस स्वयं-सेवा",
    voiceSubtitle: "माइक क्लिक करा आणि तुमची बँकिंग विनंती सांगा",
    clickMic: "बोलण्यासाठी माइक क्लिक करा",
    listening: "ऐकत आहे... आता बोला",
    processing: "तुमची विनंती प्रक्रिया होत आहे...",
    speakAgain: "पुन्हा बोलण्यासाठी माइक क्लिक करा",
    transcript: "तुमचे ट्रान्सक्रिप्ट येथे दिसेल...",
    queriesDay: "आजचे प्रश्न",
    resolutionRate: "निराकरण दर",
    avgResTime: "सरासरी निराकरण वेळ",
    escalated: "एस्केलेटेड",
    recentQueries: "अलीकडील प्रश्न",
    escalationQueue: "एस्केलेशन रांग",
    assignAgent: "एजंटला सोपवा",
    queueClear: "रांग रिकामी! सर्व ग्राहकांची सेवा झाली.",
    status: "स्थिती",
    query: "प्रश्न",
    lang: "भाषा",
    time: "वेळ",
  },
  Bengali: {
    customerChat: "গ্রাহক চ্যাট",
    adminDashboard: "অ্যাডমিন ড্যাশবোর্ড",
    voiceMode: "ভয়েস মোড",
    language: "ভাষা",
    aiOnline: "AI অনলাইন",
    assistantTracking: "সহকারী ট্র্যাকিং",
    mode: "মোড",
    typeQuery: "আপনার প্রশ্ন টাইপ করুন বা মাইক ক্লিক করুন...",
    send: "পাঠান",
    quickChips: [
      "অ্যাকাউন্ট ব্যালেন্স",
      "ফান্ড ট্রান্সফার",
      "লোন স্ট্যাটাস",
      "অভিযোগ",
      "কার্ড ব্লক",
    ],
    welcomeMsg:
      "নমস্কার! আমি BranchIQ, আপনার AI ব্যাংকিং সহকারী। বাংলায় জিজ্ঞেস করুন - অ্যাকাউন্ট ব্যালেন্স, ট্রান্সফার, লোন তথ্য পাবেন।",
    voiceTitle: "ভয়েস স্ব-সেবা",
    voiceSubtitle: "মাইক ক্লিক করুন এবং আপনার ব্যাংকিং প্রশ্ন বলুন",
    clickMic: "কথা বলতে মাইক ক্লিক করুন",
    listening: "শুনছি... এখন বলুন",
    processing: "আপনার প্রশ্ন প্রক্রিয়া হচ্ছে...",
    speakAgain: "আবার বলতে মাইক ক্লিক করুন",
    transcript: "আপনার ট্রান্সক্রিপ্ট এখানে দেখাবে...",
    queriesDay: "আজকের প্রশ্ন",
    resolutionRate: "সমাধান হার",
    avgResTime: "গড় সমাধান সময়",
    escalated: "এস্কেলেটেড",
    recentQueries: "সাম্প্রতিক প্রশ্ন",
    escalationQueue: "এস্কেলেশন কিউ",
    assignAgent: "এজেন্টকে নিযুক্ত করুন",
    queueClear: "কিউ খালি! সকল গ্রাহকদের সেবা দেওয়া হয়েছে।",
    status: "স্ট্যাটাস",
    query: "প্রশ্ন",
    lang: "ভাষা",
    time: "সময়",
  },
  Kannada: {
    customerChat: "ಗ್ರಾಹಕ ಚಾಟ್",
    adminDashboard: "ಆಡ್ಮಿನ್ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    voiceMode: "ವಾಯ್ಸ್ ಮೋಡ್",
    language: "ಭಾಷೆ",
    aiOnline: "AI ಆನ್‌ಲೈನ್",
    assistantTracking: "ಸಹಾಯಕ ಟ್ರ್ಯಾಕಿಂಗ್",
    mode: "ಮೋಡ್",
    typeQuery: "ನಿಮ್ಮ ಪ್ರಶ್ನೆ ಟೈಪ್ ಮಾಡಿ ಅಥವಾ ಮೈಕ್ ಕ್ಲಿಕ್ ಮಾಡಿ...",
    send: "ಕಳುಹಿಸಿ",
    quickChips: [
      "ಖಾತೆ ಬ್ಯಾಲೆನ್ಸ್",
      "ಫಂಡ್ ಟ್ರಾನ್ಸ್ಫರ್",
      "ಸಾಲದ ಸ್ಥಿತಿ",
      "ದೂರು",
      "ಕಾರ್ಡ್ ಬ್ಲಾಕ್",
    ],
    welcomeMsg:
      "ನಮಸ್ತೆ! ನಾನು BranchIQ, ನಿಮ್ಮ AI ಬ್ಯಾಂಕಿಂಗ್ ಸಹಾಯಕ. ಕನ್ನಡದಲ್ಲಿ ಕೇಳಿ - ಖಾತೆ ಬ್ಯಾಲೆನ್ಸ್, ವರ್ಗಾವಣೆ, ಸಾಲ ವಿವರ ಲಭ್ಯ.",
    voiceTitle: "ವಾಯ್ಸ್ ಸ್ವಯಂ-ಸೇವೆ",
    voiceSubtitle: "ಮೈಕ್ ಕ್ಲಿಕ್ ಮಾಡಿ ಮತ್ತು ನಿಮ್ಮ ಬ್ಯಾಂಕಿಂಗ್ ಪ್ರಶ್ನೆ ಹೇಳಿ",
    clickMic: "ಮಾತನಾಡಲು ಮೈಕ್ ಕ್ಲಿಕ್ ಮಾಡಿ",
    listening: "ಆಲಿಸುತ್ತಿದ್ದೇನೆ... ಇಪ್ಪೊಳ ಮಾತನಾಡಿ",
    processing: "ನಿಮ್ಮ ಪ್ರಶ್ನೆ ಪ್ರಕ್ರಿಯೆಯಾಗುತ್ತಿದೆ...",
    speakAgain: "ಮತ್ತೆ ಮಾತನಾಡಲು ಮೈಕ್ ಕ್ಲಿಕ್ ಮಾಡಿ",
    transcript: "ನಿಮ್ಮ ಟ್ರಾನ್ಸ್‌ಕ್ರಿಪ್ಟ್ ಇಲ್ಲಿ ಕಾಣಿಸುತ್ತದೆ...",
    queriesDay: "ಇಂದಿನ ಪ್ರಶ್ನೆಗಳು",
    resolutionRate: "ಪರಿಹಾರ ದರ",
    avgResTime: "ಸರಾಸರಿ ಪರಿಹಾರ ಸಮಯ",
    escalated: "ಎಸ್ಕಲೇಟೆಡ್",
    recentQueries: "ಇತ್ತೀಚಿನ ಪ್ರಶ್ನೆಗಳು",
    escalationQueue: "ಎಸ್ಕಲೇಶನ್ ಕ್ಯೂ",
    assignAgent: "ಏಜೆಂಟ್‌ಗೆ ನಿಯೋಜಿಸಿ",
    queueClear: "ಕ್ಯೂ ಖಾಲಿ! ಎಲ್ಲಾ ಗ್ರಾಹಕರಿಗೆ ಸೇವೆ ನೀಡಲಾಗಿದೆ.",
    status: "ಸ್ಥಿತಿ",
    query: "ಪ್ರಶ್ನೆ",
    lang: "ಭಾಷೆ",
    time: "ಸಮಯ",
  },
  Punjabi: {
    customerChat: "ਗਾਹਕ ਚੈਟ",
    adminDashboard: "ਐਡਮਿਨ ਡੈਸ਼ਬੋਰਡ",
    voiceMode: "ਵੌਇਸ ਮੋਡ",
    language: "ਭਾਸ਼ਾ",
    aiOnline: "AI ਔਨਲਾਈਨ",
    assistantTracking: "ਸਹਾਇਕ ਟ੍ਰੈਕਿੰਗ",
    mode: "ਮੋਡ",
    typeQuery: "ਆਪਣਾ ਸਵਾਲ ਟਾਈਪ ਕਰੋ ਜਾਂ ਮਾਈਕ ਕਲਿੱਕ ਕਰੋ...",
    send: "ਭੇਜੋ",
    quickChips: [
      "ਖਾਤਾ ਬਕਾਇਆ",
      "ਫੰਡ ਟ੍ਰਾਂਸਫਰ",
      "ਕਰਜ਼ਾ ਸਥਿਤੀ",
      "ਸ਼ਿਕਾਇਤ",
      "ਕਾਰਡ ਬਲੌਕ",
    ],
    welcomeMsg:
      "ਸਤ ਸ੍ਰੀ ਅਕਾਲ! ਮੈਂ BranchIQ ਹਾਂ, ਤੁਹਾਡਾ AI ਬੈਂਕਿੰਗ ਸਹਾਇਕ। ਪੰਜਾਬੀ ਵਿੱਚ ਪੁੱਛੋ।",
    voiceTitle: "ਵੌਇਸ ਸਵੈ-ਸੇਵਾ",
    voiceSubtitle: "ਮਾਈਕ ਕਲਿੱਕ ਕਰੋ ਅਤੇ ਆਪਣਾ ਬੈਂਕਿੰਗ ਸਵਾਲ ਬੋਲੋ",
    clickMic: "ਬੋਲਣ ਲਈ ਮਾਈਕ ਕਲਿੱਕ ਕਰੋ",
    listening: "ਸੁਣ ਰਿਹਾ ਹਾਂ... ਹੁਣ ਬੋਲੋ",
    processing: "ਤੁਹਾਡਾ ਸਵਾਲ ਪ੍ਰੋਸੈੱਸ ਹੋ ਰਿਹਾ ਹੈ...",
    speakAgain: "ਫਿਰ ਬੋਲਣ ਲਈ ਮਾਈਕ ਕਲਿੱਕ ਕਰੋ",
    transcript: "ਤੁਹਾਡਾ ਟ੍ਰਾਂਸਕ੍ਰਿਪਟ ਇੱਥੇ ਦਿਖੇਗਾ...",
    queriesDay: "ਅੱਜ ਦੇ ਸਵਾਲ",
    resolutionRate: "ਹੱਲ ਦਰ",
    avgResTime: "ਔਸਤ ਹੱਲ ਸਮਾਂ",
    escalated: "ਏਸਕਲੇਟਡ",
    recentQueries: "ਹਾਲੀਆ ਸਵਾਲ",
    escalationQueue: "ਏਸਕਲੇਸ਼ਨ ਕਤਾਰ",
    assignAgent: "ਏਜੰਟ ਨੂੰ ਸੌਂਪੋ",
    queueClear: "ਕਤਾਰ ਖਾਲੀ! ਸਾਰੇ ਗਾਹਕਾਂ ਦੀ ਸੇਵਾ ਹੋਈ।",
    status: "ਸਥਿਤੀ",
    query: "ਸਵਾਲ",
    lang: "ਭਾਸ਼ਾ",
    time: "ਸਮਾਂ",
  },
  Odia: {
    customerChat: "ଗ୍ରାହକ ଚ୍ୟାଟ",
    adminDashboard: "ଆଡ୍ମିନ ଡ୍ୟାଶବୋର୍ଡ",
    voiceMode: "ଭଏସ ମୋଡ",
    language: "ଭାଷା",
    aiOnline: "AI ଅନଲାଇନ",
    assistantTracking: "ସହାୟକ ଟ୍ରାକିଂ",
    mode: "ମୋଡ",
    typeQuery: "ଆପଣଙ୍କ ପ୍ରଶ୍ନ ଟାଇପ କରନ୍ତୁ ବା ମାଇକ୍ କ୍ଲିକ କରନ୍ତୁ...",
    send: "ପଠାନ୍ତୁ",
    quickChips: [
      "ଆକାଉଣ୍ଟ ବ୍ୟାଲେନ୍ସ",
      "ଫଣ୍ଡ ଟ୍ରାନ୍ସଫର",
      "ଋଣ ସ୍ଥିତି",
      "ଅଭିଯୋଗ",
      "କାର୍ଡ ବ୍ଲକ",
    ],
    welcomeMsg:
      "ନମସ୍କାର! ମୁଁ BranchIQ, ଆପଣଙ୍କ AI ବ୍ୟାଙ୍କିଂ ସହାୟକ। ଓଡ଼ିଆରେ ପଚାରନ୍ତୁ।",
    voiceTitle: "ଭଏସ ସ୍ୱୟଂ-ସେବା",
    voiceSubtitle: "ମାଇକ୍ କ୍ଲିକ କରନ୍ତୁ ଓ ଆପଣଙ୍କ ପ୍ରଶ୍ନ କହନ୍ତୁ",
    clickMic: "କହିବା ପାଇଁ ମାଇକ୍ କ୍ଲିକ କରନ୍ତୁ",
    listening: "ଶୁଣୁଛି... ବର୍ତ୍ତମାନ କୁହନ୍ତୁ",
    processing: "ଆପଣଙ୍କ ପ୍ରଶ୍ନ ପ୍ରକ୍ରିୟା ହେଉଛି...",
    speakAgain: "ପୁଣି କହିବା ପାଇଁ ମାଇକ୍ କ୍ଲିକ କରନ୍ତୁ",
    transcript: "ଆପଣଙ୍କ ଟ୍ରାନ୍ସକ୍ରିପ୍ଟ ଏଠି ଦେଖାଯିବ...",
    queriesDay: "ଆଜିର ପ୍ରଶ୍ନ",
    resolutionRate: "ସମାଧାନ ହାର",
    avgResTime: "ଔସତ ସମାଧାନ ସମୟ",
    escalated: "ଏସ୍କାଲେଟଡ",
    recentQueries: "ସାମ୍ପ୍ରତିକ ପ୍ରଶ୍ନ",
    escalationQueue: "ଏସ୍କାଲେଶନ ଧାଡ଼ି",
    assignAgent: "ଏଜେଣ୍ଟଙ୍କୁ ସୋଂପ",
    queueClear: "ଧାଡ଼ି ଖାଲି! ସବୁ ଗ୍ରାହକଙ୍କ ସେବା ହୋଇଛି।",
    status: "ସ୍ଥିତି",
    query: "ପ୍ରଶ୍ନ",
    lang: "ଭାଷା",
    time: "ସମୟ",
  },
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState("English");
  return (
    <LanguageContext.Provider value={{ language, setLanguage }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);

// Helper hook: t('key') → translated string for current language
export const useT = () => {
  const { language } = useLanguage();
  return (key) => (UI_STRINGS[language] || UI_STRINGS.English)[key] || key;
};
